services:
  web:
    image: 337405469571.dkr.ecr.ap-southeast-2.amazonaws.com/health-api
    container_name: python-app
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis-server
